const dummyDocuments = [
  {
    id: 1,
    name: "ActiveProcure.docx",
    recognition: "Monthly",
    payment: "Net 30",
    pricing: "Fixed",
    renewal: true,
    termination: "60 days",
  },
  {
    id: 2,
    name: "FastSolutions.pdf",
    recognition: "Milestone-based",
    payment: "Net 45",
    pricing: "Variable",
    renewal: false,
    termination: "30 days",
  },
  {
    id: 3,
    name: "MarkPointSoftw...",
    recognition: "Monthly",
    payment: "Net 15",
    pricing: "Tiered",
    renewal: true,
    termination: "90 days",
  },
  {
    id: 4,
    name: "GreenFlowOp.docx",
    recognition: "Upfront",
    payment: "Net 60",
    pricing: "Fixed",
    renewal: true,
    termination: "Immediate",
  },
  {
    id: 5,
    name: "Leteria-20.pdf",
    recognition: "Usage-based",
    payment: "Net 30",
    pricing: "Subscription",
    renewal: true,
    termination: "45 days",
  },
  {
    id: 6,
    name: "SylonSynergySign...",
    recognition: "Quarterly",
    payment: "Net 60",
    pricing: "Fixed",
    renewal: false,
    termination: "60 days",
  },
  {
    id: 7,
    name: "True-Allocation-2...",
    recognition: "Milestone-based",
    payment: "Net 45",
    pricing: "Property",
    renewal: true,
    termination: "30 days",
  },
  {
    id: 8,
    name: "EmberkableLego...",
    recognition: "Monthly",
    payment: "Net 90",
    pricing: "Fixed",
    renewal: true,
    termination: "60 days",
  },
  {
    id: 9,
    name: "ForwardLearningOl...",
    recognition: "Upfront",
    payment: "Net 30",
    pricing: "Variable",
    renewal: true,
    termination: "90 days",
  },
  {
    id: 10,
    name: "LegDraft_2024_06...",
    recognition: "Usage-based",
    payment: "Net 60",
    pricing: "Tiered",
    renewal: false,
    termination: "45 days",
  },
  {
    id: 11,
    name: "Calmation_2023_1...",
    recognition: "Monthly",
    payment: "Net 45",
    pricing: "Subscription",
    renewal: true,
    termination: "Immediate",
  },
];

export default dummyDocuments;
